using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Graphics;
using Microsoft.Xna.Framework.Input;
using RecrownedAthenaeum.Render;
using RecrownedAthenaeum.ContentSystem;
using RecrownedAthenaeum.Input;
using RecrownedAthenaeum.Persistence;
using RecrownedAthenaeum.UI.ScreenSystem;
using RecrownedAthenaeum.SpecialTypes;
using RecrownedAthenaeum.UI.SkinSystem;
using RecrownedAthenaeum.UI.SkinSystem.Definitions;
using RhythmBullet.Audio;
using RhythmBullet.ContentResolvers;
using RhythmBullet.Preferences;
using RhythmBullet.Screens.MainMenu;
using System;
using System.Diagnostics;
using System.IO;

namespace RhythmBullet
{
    /// <summary>
    /// This is the main type for your game.
    /// </summary>
    public class RhythmBulletGame : Game
    {
        public const int WORLD_WIDTH = 4;
        public const int WORLD_HEIGHT = 3;
        public static int pixels_per_WU;

        GraphicsDeviceManager graphics;
        ConsistentSpriteBatch spriteBatch;
        public readonly ContentManagerController assets;
        public PreferencesManager preferencesManager;
        private ScreenManager screenManager;
        public Camera2D Camera { get; private set; }
        public BasicEffect cameraEffect;
        private MainScreen mainScreen;
        private Texture2D currentCursorTexture;
        internal readonly MusicController musicController;
        private SkinManager skinManager = new SkinManager();
        private ISkin Skin { get { return skinManager.Skin; } }
        private ResolutionContentResolver resolutionContentResolver = new ResolutionContentResolver();
        private FontContentResolver fontContentResolver;
        public RhythmBulletGame()
        {
            graphics = new GraphicsDeviceManager(this);
            Content.RootDirectory = "Content";
            assets = new ContentManagerController(Content);
            //Add the content resolvers.
            assets.AddContentPathResolver(typeof(Texture2D), resolutionContentResolver);
            fontContentResolver = new FontContentResolver(resolutionContentResolver);
            assets.AddContentPathResolver(typeof(SpriteFont), fontContentResolver);

            musicController = new MusicController();
            preferencesManager = new PreferencesManager(
                Environment.GetFolderPath(Environment.SpecialFolder.ApplicationData) + "/RhythmBullet",
                new General(),
                new Controls());
            preferencesManager.Load();
            Resolution resolution = preferencesManager.GetPreferences<General>().Resolution;
            graphics.PreferredBackBufferWidth = resolution.Width;
            graphics.PreferredBackBufferHeight = resolution.Height;
            
        }

        /// <summary>
        /// Allows the game to perform any initialization it needs to before starting to run.
        /// This is where it can query for any required services and load any non-graphic
        /// related content. Calling base.Initialize will enumerate through any components
        /// and initialize them as well.
        /// </summary>
        protected override void Initialize()
        {
            General general = preferencesManager.GetPreferences<General>();
            Resolution resolution = general.Resolution;
            musicController.musicList.path = general.MusicDirectory;
            musicController.musicList.StartSearch();
            if ((general.skinName) != null)
            {
                skinManager.LoadSkin(Path.Combine(general.skinDirectory, general.skinName), graphics.GraphicsDevice);
            }

            Debug.WriteLine("Initial resolution: " + resolution);
            cameraEffect = new BasicEffect(graphics.GraphicsDevice);
            cameraEffect.TextureEnabled = true;
            cameraEffect.VertexColorEnabled = true;
            Camera = new Camera2D(resolution.Width, resolution.Height, cameraEffect);
            Debug.WriteLine("Initial setup complete.");
            base.Initialize();
            
        }

        /// <summary>
        /// LoadContent will be called once per game and is the place to load
        /// all of your content.
        /// </summary>
        protected override void LoadContent()
        {
            // Create a new SpriteBatch, which can be used to draw textures.
            spriteBatch = new ConsistentSpriteBatch(GraphicsDevice);

            screenManager = new ScreenManager(graphics);
            screenManager.NeedNextScreen += ShowFirstScreen;
            General general = preferencesManager.GetPreferences<General>();
            Resolution resolution = general.Resolution;
            QueueContent();
            resolutionContentResolver.Height = resolution.Height;
            resolutionContentResolver.Width = resolution.Width;
            screenManager.Screen = new LoadingScreen(this, Content.Load<Texture2D>("RhythmBullet"), 0.7f);
        }

        /// <summary>
        /// UnloadContent will be called once per game and is the place to unload
        /// game-specific content.
        /// </summary>
        protected override void UnloadContent()
        {
            assets.UnloadAll();
            screenManager.Dispose();
            currentCursorTexture.Dispose();
        }

        /// <summary>
        /// Allows the game to run logic such as updating the world,
        /// checking for collisions, gathering input, and playing audio.   
        /// </summary>
        /// <param name="gameTime">Provides a snapshot of timing values.</param>
        protected override void Update(GameTime gameTime)
        {
            if (!assets.Done)
            {
                assets.Update();
            }
            else if (CheckReadyForInitiate())
            {
                PostLoad();
            }
            else
            {
                assets.Update();
            }
            screenManager.UpdateCurrentScreen(gameTime, !CheckReadyForInitiate());

            InputUtilities.Update();
            base.Update(gameTime);
        }

        /// <summary>
        /// This is called when the game should draw itself.
        /// </summary>
        /// <param name="gameTime">Provides a snapshot of timing values.</param>
        protected override void Draw(GameTime gameTime)
        {
            spriteBatch.effect = cameraEffect;
            screenManager.DrawScreen(spriteBatch);
            base.Draw(gameTime);
        }

        /// <summary>
        /// Updates the world constants, unloads all assets, queues the new batch, and resizes the virtual screens.
        /// Finishes by updating the cursor size.
        /// </summary>
        /// <param name="width">New window width.</param>
        /// <param name="height">New window height.</param>
        public void Resize(int width, int height)
        {
            pixels_per_WU = height / WORLD_HEIGHT;
            graphics.PreferredBackBufferWidth = width;
            graphics.PreferredBackBufferHeight = height;
            assets.UnloadAll();
            resolutionContentResolver.Height = height;
            resolutionContentResolver.Width = width;
            QueueContent();
            screenManager.Resize(new LoadingScreen(this, Content.Load<Texture2D>("loading_ring"), 0.4f, true));
            UpdateCursor();
        }

        private void PostResize()
        {
            graphics.ApplyChanges();
            Camera.Apply();
            screenManager.PostResize();
        }

        private bool CheckReadyForInitiate()
        {
            bool ready = true;
            if (!assets.Done || !musicController.musicList.Searched)
            {
                ready = false;
            }

            if (preferencesManager.GetPreferences<General>().skinName != null && !skinManager.MergingSkins)
            {
                ready = false;
            }
            return ready;
        }

        private void ShowFirstScreen(Screen Screen)
        {
            Screen.NextScreen = mainScreen;
        }

        private void QueueContent()
        {
            assets.Queue<Texture2D>("cursor", false);
            assets.Queue<Texture2D>("title", false);
            assets.Queue<Texture2D>("default_cover", false);
            assets.Queue<TextureAtlas>("UI");
            assets.Queue<SpriteFont>("gasalt_regular");
            assets.Queue<SpriteFont>("darktech_ldr");
            assets.Queue<SpriteFont>("iron_maiden");
        }

        private void PostLoad()
        {
            Debug.WriteLine("Initial setup and loading complete.");
            SetUpDefaultSkin();
            UpdateCursor();

            mainScreen = new MainScreen(assets, Skin, Camera);
        }

        private void UpdateCursor()
        {
            SpriteBatch spriteBatch = this.spriteBatch;
            Texture2D texture = Skin.CursorTexture;
            int cursorSize = (int)(0.07f * graphics.PreferredBackBufferHeight);
            Debug.WriteLine("Cursor size length: " + cursorSize);
            RenderTarget2D renderTarget = new RenderTarget2D(GraphicsDevice, cursorSize, cursorSize);
            GraphicsDevice.SetRenderTarget(renderTarget);
            GraphicsDevice.Clear(Color.Transparent);
            spriteBatch.Begin();
            spriteBatch.Draw(texture, new Rectangle(0, 0, cursorSize, cursorSize), Color.White);
            spriteBatch.End();
            GraphicsDevice.SetRenderTarget(null);

            currentCursorTexture?.Dispose();
            currentCursorTexture = renderTarget;
            Mouse.SetCursor(MouseCursor.FromTexture2D(currentCursorTexture, currentCursorTexture.Width / 2, currentCursorTexture.Height / 2));
        }

        private void SetUpDefaultSkin()
        {
            Skin skin = new Skin(assets.Get<TextureAtlas>("UI"), assets.Get<Texture2D>("cursor"));
            skin.AddColor("default", Color.White);

            TextButtonSkinDefinition textButtonSkinDefinition = new TextButtonSkinDefinition("rectangle-button-down", "rectangle-button");
            textButtonSkinDefinition.selectedRegion = "rectangle-button-highlighted";
            textButtonSkinDefinition.disabledRegion = "rectangle-button-disabled";

            skin.AddDefinition(textButtonSkinDefinition);

            skin.Laminate();
            skinManager.BaseSkin = skin;
        }
    }
}
